# pay_pal_restap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PayPalRestapIs
  # Represents a single Http Request.
  class HttpRequest < CoreLibrary::HttpRequest
  end
end
