# pay_pal_restap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PayPalRestapIs
  # Http response received.
  class HttpResponse < CoreLibrary::HttpResponse
  end
end
