# pay_pal_restap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PayPalRestapIs
  # A Resource representing a response of vaulted a ACH Debit Account.
  class ACHDebitResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The ach debit verification status.
    # @return [String]
    attr_accessor :verification_status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['verification_status'] = 'verification_status'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        verification_status
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(verification_status = 'NOT_VERIFIED')
      @verification_status = verification_status unless verification_status == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      verification_status = hash['verification_status'] ||= 'NOT_VERIFIED'

      # Create object from extracted values.
      ACHDebitResponse.new(verification_status)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} verification_status: #{@verification_status}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} verification_status: #{@verification_status.inspect}>"
    end
  end
end
