# pay_pal_restap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PayPalRestapIs
  # The authorization status of the wallet instrument.
  class InstrumentAuthorizationStatus
    INSTRUMENT_AUTHORIZATION_STATUS = [
      # TODO: Write general description for AUTHORIZED
      AUTHORIZED = 'AUTHORIZED'.freeze,

      # TODO: Write general description for BLOCKED
      BLOCKED = 'BLOCKED'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'FAILED'.freeze,

      # TODO: Write general description for NOT_APPLICABLE
      NOT_APPLICABLE = 'NOT_APPLICABLE'.freeze,

      # TODO: Write general description for NOT_SUPPORTED
      NOT_SUPPORTED = 'NOT_SUPPORTED'.freeze,

      # TODO: Write general description for UNAUTHORIZED
      UNAUTHORIZED = 'UNAUTHORIZED'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
