# pay_pal_restap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PayPalRestapIs
  # Configures a <strong>Continue</strong> or <strong>Pay Now</strong> checkout
  # flow.
  class PayPalExperienceUserAction
    PAY_PAL_EXPERIENCE_USER_ACTION = [
      # TODO: Write general description for CONTINUE
      CONTINUE = 'CONTINUE'.freeze,

      # TODO: Write general description for PAY_NOW
      PAY_NOW = 'PAY_NOW'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end
  end
end
