# pay_pal_restap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PayPalRestapIs
  # An API resource used in the response of securely storing a SEPA Debit.
  class VaultSEPADebitResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The last characters of the IBAN used to pay.
    # @return [String]
    attr_accessor :iban_last_chars

    # The last characters of the IBAN used to pay.
    # @return [Object]
    attr_accessor :account_holder_name

    # The portable international postal address. Maps to
    # [AddressValidationMetadata](https://github.com/googlei18n/libaddressinput/
    # wiki/AddressValidationMetadata) and HTML 5.1 [Autofilling form controls:
    # the autocomplete
    # attribute](https://www.w3.org/TR/html51/sec-forms.html#autofilling-form-co
    # ntrols-the-autocomplete-attribute).
    # @return [Address]
    attr_accessor :billing_address

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['iban_last_chars'] = 'iban_last_chars'
      @_hash['account_holder_name'] = 'account_holder_name'
      @_hash['billing_address'] = 'billing_address'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        iban_last_chars
        account_holder_name
        billing_address
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(iban_last_chars = SKIP, account_holder_name = SKIP,
                   billing_address = SKIP)
      @iban_last_chars = iban_last_chars unless iban_last_chars == SKIP
      @account_holder_name = account_holder_name unless account_holder_name == SKIP
      @billing_address = billing_address unless billing_address == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      iban_last_chars =
        hash.key?('iban_last_chars') ? hash['iban_last_chars'] : SKIP
      account_holder_name =
        hash.key?('account_holder_name') ? hash['account_holder_name'] : SKIP
      billing_address = Address.from_hash(hash['billing_address']) if hash['billing_address']

      # Create object from extracted values.
      VaultSEPADebitResponse.new(iban_last_chars,
                                 account_holder_name,
                                 billing_address)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} iban_last_chars: #{@iban_last_chars}, account_holder_name:"\
      " #{@account_holder_name}, billing_address: #{@billing_address}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} iban_last_chars: #{@iban_last_chars.inspect}, account_holder_name:"\
      " #{@account_holder_name.inspect}, billing_address: #{@billing_address.inspect}>"
    end
  end
end
