# pay_pal_restap_is
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PayPalRestapIs
  # API utility class
  class APIHelper < CoreLibrary::ApiHelper
  end
end
